name: The name of your action here
description: Provide a description here
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  tenantId:
    description: Tenant Id for the SharePoint Online Tenant
    required: true
  clientId:
    description: Client Id for the Azure AD App Registration
    required: true
  siteUrl:
    description: The URL of the SharePoint site to deploy the package to
    required: true
  packagePath:
    description: The path to the SPFx package to deploy
    required: true
  certBase64Encoded:
    description: Base64 encoded certificate for the Azure AD App Registration
    required: true
  thumbprint:
    description: Thumbprint of the certificate for the Azure AD App Registration
    required: true
  scopes:
    description: List of scopes to use - seperated by comman.
    required: true

# Define your outputs here.
outputs:
  result:
    description: The result of the deployment

runs:
  using: node20
  main: dist/index.js
